version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          command: |
            sudo apt-get -y -qq install python-pip imagemagick
            sudo pip install fonttools
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          command: |
            npm run publish
